### ISSUE TITLE
Use different gomplate syntax for config/secret values to avoid newline and quote problems

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/k-apis#47]
For example:

```yaml
apiVersion: qlik.com/v1
kind: SelectivePatch
metadata:
  name: identity-providers-generated-operator-secrets
enabled: true
patches:
- patch: |
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: identity-providers-secrets
    stringData:
      idpConfigs: '(( (ds "data").idpConfigs | regexp.Replace "[\r\n]+" "\\n" | strings.Squote | strings.TrimPrefix "'" | strings.TrimSuffix "'" ))'
  target:
    kind: SuperSecret
    labelSelector: app=identity-providers
```

replace the new lines with new line chars, double the single quotes so that it can be wrapped in a single quote string.. then trim the extraneous single quotes (added by Squote), added to allow the gomplate syntax to work
