### ISSUE TITLE
change the way patch generated for secrets

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/k-apis#77]
existing way
```
- patch: |
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: qliksense-secrets
    stringData:
      dockerConfigJson: |-
        ((- "\n"))(( index (ds "data") "dockerConfigJson" | base64.Decode | indent 8 ))
  target:
    kind: SuperSecret
    labelSelector: app=qliksense
```

proposed new way
```
- patch: |
    apiVersion: qlik.com/v1
    kind: SuperSecret
    metadata:
      name: qliksense-secrets
    data:
      dockerConfigJson: (( index (ds "data") "dockerConfigJson" ))
  target:
    kind: SuperSecret
    labelSelector: app=qliksense
```
